version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: PostgreSQL
    restart: always
    environment:
      POSTGRES_DB: local
      POSTGRES_USER: usuario_aqui
      POSTGRES_PASSWORD: password_aqui
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local

