version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: SQL-Server
    environment:
      - ACCEPT_EULA="Y"
      - MSSQL_SA_PASSWORD=password_aqui
      - MSSQL_PID=Developer
      # - MSSQL_LCID=13322  # Establece el idioma en español latinoamericano
    ports:
      - "1433:1433"
    volumes:
      - ./sqldata:/var/opt/mssql
volumes:
  sqldata:

